spring:
  application:
    name: demoTest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.1.66:3306/testbatch
    username: root
    password: Admin@A123
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  sql:
    init:
      mode: always
  batch:
    jdbc:
      initialize-schema: always